# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Website
    url: https://builtview.com
  - name: Web app
    url: https://app.builtview.com
  - name: Backend server
    url: https://api.buitlview.com/api/ping
  - name: Authentication
    url: https://builtview.b2clogin.com/builtview.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_SIGNUP_SIGNIN

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /builtview/status-page
  logoUrl: https://assets-global.website-files.com/6152ad87336c330bd1d4d50c/651f5592acd1cf1eb6a492a6_BV_Logo_HRZ_WHT2.svg
  name: BuiltView
  introTitle: "BuiltView - Building confidence"
  introMessage: This status page uses **real-time** data
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://builtview.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
